name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up openJDK
        uses: joschi/setup-jdk@v2
        with:
          java-version: '14'
      - name: Delete jar-file
        run: make clean
      - name: Build with Maven
        run: mvn -B package --file pom.xml
